spring:
  datasource:
    url: jdbc:mysql://zeusfit.mysql.database.azure.com:3306/${dbname}?useSSL=true
    username: zeusfit
    password: SSDProject9
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect : org.hibernate.dialect.MySQLInnoDBDialect

server:
  port: 8080



