spring:
  datasource:
    url: jdbc:mysql://zeusfit.mysql.database.azure.com:3306/zeusfit?useSSL=true
    username: ###
    password: ####
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQLInnoDBDialect

server:
  port: 8080
  


