spring:
  datasource:
    url: jdbc:mysql://zeusfit.mysql.database.azure.com:3306/${DB-Name}?useSSL=true
    username: zeusfit
    password: SSDProject9
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect : org.hibernate.dialect.MySQLInnoDBDialect

server:
  port: 8080

azure:
  keyvault:
    enabled: true
    uri: https://zeusfitkeyvault.vault.azure.net/
    client-id: 01289cb1-2bbc-4327-a16d-30cc4b1c757e
    client-key: uwgNC~_QLwjjBcDHe2VhyTWViXguH6AL6~
    tenant-id: 2fcfe26a-bb62-46b0-b1e3-28f9da0c45fd


